spring:
  h2:
    console:
      enabled: true
  datasource:
    url:jdbc:h2:mem:testdb

#server:
#  port: 8080

server:
  port: 443
  ssl:
    key-store: classpath:mkyong.p12
    key-store-password: 123456
    key-store-type: PKCS12


logging:
  level:
    org.springframework: ERROR
    com.gsf.client.api: DEBUG
  pattern:
    console: "%d{HH:mm:ss.SSS} [%t] %-5level %logger{36} - %msg%n"
    file: "%d %p %c{1.} [%t] %m%n"
  file: C:/dev/dummy-authorization-server.log


  # security.require-ssl=true