@startuml
!define LIGHTBLUE
!includeurl https://raw.githubusercontent.com/Drakemor/RedDress-PlantUML/master/style.puml

'diagram title'
title Ataque **CSRF (Cross Site Request Forgery)** no OAuth 2.0 Authorization Code Grant
autonumber

legend top
      O **CSRF (Cross Site Request Forgery)** é uma vulnerabilidade de segurança na web que
      permite que um invasor induza o usuário a realizar ações que eles não pretendem realizar.
end legend

actor "Vitima \n**(Browser)**" as VITIMA #LightBlue

actor "Attacker \n**(Browser)**" as USER #Red

box
  participant "Client\n"  as CLIENT  #LightBlue
end box

box
  participant "Authorization Server\n **(AS)**" as AS #LightBlue
  participant "Resource Server\n **(RS)**" as RS #LightBlue
end box

'passo 1
USER -> CLIENT: **POST** www.site.com

'passo 2
CLIENT --> USER: 302 Redirect
    note left of  CLIENT #LightYellow
        //Client// redireciona //Attacker// para o AS **/oauth2/authorize**
        passando client_id, redirect_uri
    end note

'passo 3
USER -> AS: **GET** /oauth2/authorize?response_type=code&\nredirect_uri=/callback&client_id=abc

'passo 4
AS --> USER: 302 Redirect
  note left of  AS #LightYellow
        AS utiliza **redirect_uri** para retornar ao //Attacker//
        tela para efetuar longin
    end note

'passo 5
USER -> AS: **POST** /login
    note right of  USER #LightYellow
        //Attacker// efetua login no AS com **username, password**
    end note

'passo 6
AS --> USER: 302 Redirect redirect_uri + <font color=red>authorization_code

'passo 7
USER x->? : **GET** redirect_uri, <font color=red>authorization_code
    note right of  USER #LightYellow
        //Attacker// intercepta redirecionamento
        para o Client e envia o //link// para a Vítima
    end note


'passo 8
USER -> VITIMA: **GET** redirect_uri, <font color=red>authorization_code

'passo 9
VITIMA -> CLIENT: **GET** redirect_uri, <font color=red>authorization_code

'passo 10
CLIENT -> AS:**POST** /oauth2/token <font color=red>authorization_code

'passo 11
AS -> CLIENT: 200 OK **acess_token**
    note left of  AS #LightYellow
        Tudo que a Vitima fizer será feito em beneficio do //Attacker//
    end note

'passo 12
CLIENT -> RS: **GET** /resource

'passo 13
RS -> CLIENT: 200 OK recurso protegido

@enduml
