version: "3.5"
services:
  keyrock:
    #image: fiware/idm:7.9.2
    image: idm-security-image
    #image: fiware/idm:7.8.1
    container_name: fiware-keyrock-security
    hostname: keyrock
    networks:
      default-security:
        ipv4_address: 172.18.2.5
    depends_on:
      - mysql-db-security
    ports:
      - "3105:3105"
      - "443:443"
    environment:
      - DEBUG=idm:*
      - IDM_DB_HOST=mysql-db-security
      - IDM_HOST=http://localhost:3105
      - IDM_PORT=3105
      # Development use only 
      # Use Docker Secrets for Sensitive Data
      - IDM_DB_PASS=secret 
      - IDM_DB_USER=root
      - IDM_ADMIN_USER=admin
      - IDM_ADMIN_EMAIL=admin@test.com
      - IDM_ADMIN_PASS=1234
      # If sending eMails point to any STMP server
      #- IDM_EMAIL_HOST=mailer
      #- IDM_EMAIL_PORT=25
      - path_to_file:/opt/fiware-idm/config.js


  mysql-db-security:
    restart: always
    image: mysql:5.7
    hostname: mysql-db-security
    container_name: db-mysql-security
    expose:
      - "3307"
    ports:
      - "3307:3307"
    networks:
      default-security:
        ipv4_address: 172.18.2.6
    environment:
      # Development use only 
      # Use Docker Secrets for Sensitive Data
      - "MYSQL_ROOT_PASSWORD=secret"
      - "MYSQL_ROOT_HOST=172.18.2.5"
    volumes:
      - mysql-db-security:/var/lib/mysql
     
networks:
  default-security:
    ipam:
      config:
        - subnet: 172.18.2.0/24
volumes:
  mysql-db-security: ~
