version: '3.5'
services:
    keyrock:
        #image: fiware/idm:7.6.0
        image: idm-fiware-image 
        container_name: fiware-keyrock
        hostname: keyrock
        networks:
            default-vulnerable:
                ipv4_address: 192.18.1.5
        depends_on:
            - mysql-db-vulnerable
        ports:
            - '3105:3105'
            - '443:443'
        environment:
            - DEBUG=idm:*
            - IDM_DB_HOST=mysql-db
            - IDM_HOST=http://localhost:3105
            - IDM_PORT=3105
            # Development use only
            # Use Docker Secrets for Sensitive Data
            - IDM_DB_PASS=secret
            - IDM_DB_USER=root
            - IDM_ADMIN_USER=admin
            - IDM_ADMIN_EMAIL=admin@test.com
            - IDM_ADMIN_PASS=1234
            # If sending eMails point to any STMP server
            #- IDM_EMAIL_HOST=mailer
            #- IDM_EMAIL_PORT=25

    mysql-db-vulnerable:
        restart: always
        image: mysql:5.7
        hostname: mysql-db-vulnerable
        container_name: db-mysql-vulnerable
        expose:
            - '3309'
        ports:
            - '3309:3306'
        networks:
            default-vulnerable:
                ipv4_address: 192.18.1.6
        environment:
            # Development use only
            # Use Docker Secrets for Sensitive Data
            - 'MYSQL_ROOT_PASSWORD=secret'
            - 'MYSQL_ROOT_HOST=192.18.1.5'
        volumes:
            - mysql-db-vulnerable:/var/lib/mysql
            - ./mysql-data:/docker-entrypoint-initdb.d/:ro
    
networks:
    default-vulnerable:
        ipam:
            config:
                - subnet: 192.18.1.0/24
volumes:
    mysql-db-vulnerable: ~