spring:
  h2:
    console:
      enabled: true
  datasource:
    url:jdbc:h2:mem:testdb


server:
  port: 9191

logging:
  level:
    org.springframework: ERROR
    com.gsf.executor.api: DEBUG
  pattern:
    console: "%d{HH:mm:ss.SSS} [%t] %-5level %logger{36} - %msg%n"
    file: "%d %p %c{1.} [%t] %m%n"
  file: C:/dev/oauth-manager.log

oauthmanager:
    users: C:/dev/docker/oauth-fiware/oauth-manager/src/main/resources/user-template.json
    captureFile: C:/dev/docker/oauth-fiware/fiware-idm/tcpdump/tcpdump.pcap
    captureFileHTTPS: C:/dev/docker/oauth-fiware/dummy-https/tcpdump/tcpdump.pcap