spring:
  h2:
    console:
      enabled: true
  datasource:
    url:jdbc:h2:mem:testdb

server:
  port: 9001

logging:
  level:
    org.springframework: ERROR
    com.gsf.client.api: DEBUG
  pattern:
    console: "%d{HH:mm:ss.SSS} [%t] %-5level %logger{36} - %msg%n"
    file: "%d %p %c{1.} [%t] %m%n"
  file: C:/dev/dummy-client.log

oauthmanager:
  clients: src/main/resources/client-template.json